(() => {
  "use strict";
  const cfg = window.ZTORRENT_CONFIG || {};
  const API = String(cfg.API_BASE_URL || "").replace(/\/+$/, "");
  const MAX_BROWSER = Number(cfg.MAX_BROWSER_ASSEMBLY_BYTES || 256 * 1024 * 1024);
  const POLL_MS = Number(cfg.POLL_INTERVAL_MS || 1000);
  const $ = (id) => document.getElementById(id);
  const ui = { form:$("gatewayForm"),input:$("sourceInput"),paste:$("pasteButton"),clear:$("clearButton"),analyze:$("analyzeButton"),workspace:$("workspace"),mode:$("modePill"),install:$("installButton"),jobTitle:$("jobTitle"),jobType:$("jobType"),filename:$("jobFilename"),state:$("stateBadge"),progress:$("progressBar"),progressNumber:$("progressNumber"),sourceSpeed:$("sourceSpeed"),sourceSpeedHint:$("sourceSpeedHint"),deliverySpeed:$("deliverySpeed"),deliverySpeedHint:$("deliverySpeedHint"),connections:$("connections"),connectionsHint:$("connectionsHint"),remaining:$("remaining"),sizeHint:$("sizeHint"),diagnostics:$("diagnostics"),engineName:$("engineName"),engineDescription:$("engineDescription"),integrityName:$("integrityName"),integrityDescription:$("integrityDescription"),download:$("downloadButton"),pause:$("pauseButton"),resume:$("resumeButton"),cancel:$("cancelButton"),toast:$("toast") };
  let currentJob=null,pollTimer=null,webTorrentClient=null,installPrompt=null;
  function toast(message){ui.toast.textContent=message;ui.toast.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(()=>ui.toast.classList.remove("show"),2400)}
  function setMode(){const text=ui.mode.querySelector("span");if(API){ui.mode.classList.add("backend");text.textContent="Accelerator Mode"}else{ui.mode.classList.remove("backend");text.textContent="Browser Mode"}}
  function classify(value){const v=value.trim();if(/^magnet:\?/i.test(v))return"magnet";if(/^https?:\/\/.+\.torrent(?:[?#]|$)/i.test(v))return"torrent";if(/^https?:\/\/.+\.(?:meta4|metalink)(?:[?#]|$)/i.test(v))return"metalink";if(/^https?:\/\//i.test(v))return"http";return"unknown"}
  function prettyBytes(n){n=Number(n);if(!Number.isFinite(n)||n<0)return"—";const units=["B","KB","MB","GB","TB"];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return`${n>=100||i===0?n.toFixed(0):n.toFixed(1)} ${units[i]}`}
  function prettySpeed(n){return Number.isFinite(Number(n))?`${prettyBytes(Number(n))}/s`:"—"}
  function filenameFromUrl(url){try{const p=new URL(url).pathname.split("/").filter(Boolean).pop();return decodeURIComponent(p||"download")}catch{return"download"}}
  function showWorkspace(){ui.workspace.hidden=false;ui.workspace.scrollIntoView({behavior:"smooth",block:"start"})}
  function state(label,tone="ok"){ui.state.textContent=label.toUpperCase();ui.state.style.color=tone==="bad"?"var(--danger)":tone==="warn"?"#e4c272":"var(--accent)"}
  function setProgress(value){const n=Math.max(0,Math.min(100,Number(value)||0));ui.progress.style.width=`${n}%`;ui.progressNumber.textContent=`${n.toFixed(n<10&&n>0?1:0)}%`}
  function diag(label,value,tone="ok"){const row=document.createElement("div");row.className="diagnostic";const left=document.createElement("span"),right=document.createElement("span");right.className=tone;left.textContent=label;right.textContent=value;row.append(left,right);ui.diagnostics.appendChild(row)}
  function resetJobUi(){clearInterval(pollTimer);pollTimer=null;ui.diagnostics.innerHTML="";ui.download.hidden=ui.pause.hidden=ui.resume.hidden=ui.cancel.hidden=true;ui.jobTitle.textContent="Analyzing source";ui.filename.textContent="Resolving…";ui.jobType.textContent="AUTO DETECT";ui.sourceSpeed.textContent=ui.deliverySpeed.textContent=ui.connections.textContent=ui.remaining.textContent="—";ui.sourceSpeedHint.textContent="Waiting for source";ui.deliverySpeedHint.textContent="Not measured yet";ui.connectionsHint.textContent="Automatic";ui.sizeHint.textContent="Size unknown";ui.engineName.textContent="Automatic";ui.engineDescription.textContent="Ztorrent will choose the strongest available transport.";setProgress(0);state("Analyzing")}
  async function backendAnalyze(source){const r=await fetch(`${API}/v1/analyze`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Analyze failed (${r.status})`);return body}
  async function browserAnalyze(source){const type=classify(source);if(type==="unknown")throw new Error("Use an HTTP(S) URL or magnet link.");if(type==="magnet"){const params=new URLSearchParams(source.slice(source.indexOf("?")+1));return{type:"magnet",filename:params.get("dn")||"Torrent download",engine:"WebTorrent / WebRTC",range_supported:false,backend_recommended:true,note:"Browser torrent mode can only reach WebRTC-compatible peers."}}const base={type,filename:filenameFromUrl(source),engine:"Direct HTTP",range_supported:false,backend_recommended:true};try{let r=await fetch(source,{method:"HEAD",mode:"cors",cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const len=Number(r.headers.get("content-length"));const ranges=/bytes/i.test(r.headers.get("accept-ranges")||"");return{...base,final_url:r.url||source,size:Number.isFinite(len)?len:null,content_type:r.headers.get("content-type"),etag:r.headers.get("etag"),range_supported:ranges,engine:ranges?"Browser segmented HTTP":"Direct HTTP",backend_recommended:!ranges||(Number.isFinite(len)&&len>MAX_BROWSER)}}catch(e){return{...base,cors_blocked:true,note:"The browser could not probe this cross-origin source. Direct download may still work."}}}
  function renderAnalysis(a){const typeLabel=({magnet:"BITTORRENT MAGNET",torrent:"TORRENT FILE",metalink:"METALINK",http:"HTTP / HTTPS"})[a.type]||a.type;ui.jobType.textContent=typeLabel||"SOURCE";ui.filename.textContent=a.filename||"download";ui.jobTitle.textContent="Source resolved";ui.engineName.textContent=a.engine||"Automatic";ui.engineDescription=a.type==="magnet"?(API?"Server-side BitTorrent through aria2, then resumable HTTPS delivery.":"Browser WebTorrent uses WebRTC peers only; Accelerator Mode reaches the normal swarm."):a.range_supported?"Byte-range capable source detected. Parallel segments are available where permitted.":"Single-stream/direct delivery unless the backend finds a stronger supported path.";ui.integrityName.textContent=a.etag?"ETag locked":a.type==="magnet"?"Piece hashes":"Source guarded";if(a.size){ui.remaining.textContent=prettyBytes(a.size);ui.sizeHint.textContent=`${prettyBytes(a.size)} total`}diag("Source type",typeLabel||"Unknown","ok");if(a.size)diag("File size",prettyBytes(a.size),"ok");if(a.range_supported)diag("HTTP byte ranges","SUPPORTED","ok");else if(a.type==="http")diag("HTTP byte ranges",a.cors_blocked?"UNVERIFIED":"NOT ADVERTISED","warn");if(a.etag)diag("Version lock","ETag available","ok");if(a.cors_blocked)diag("Browser probe","CORS restricted","warn");if(a.backend_recommended&&!API)diag("Accelerator service","Recommended for this source","warn");if(a.note)diag("Engine note",a.note,"warn")}
  async function createBackendJob(source){const r=await fetch(`${API}/v1/jobs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Could not start job (${r.status})`);currentJob=body;ui.jobTitle.textContent="Accelerating";ui.cancel.hidden=false;ui.pause.hidden=false;state("Downloading");await pollBackendJob();pollTimer=setInterval(pollBackendJob,POLL_MS)}
  async function pollBackendJob(){if(!currentJob?.id)return;try{const r=await fetch(`${API}/v1/jobs/${encodeURIComponent(currentJob.id)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Status request failed");currentJob=j;const total=Number(j.total_bytes||0),done=Number(j.completed_bytes||0);setProgress(total>0?done/total*100:0);ui.filename.textContent=j.filename||ui.filename.textContent;ui.sourceSpeed.textContent=prettySpeed(j.download_speed);ui.sourceSpeedHint.textContent=j.status==="active"?"Live engine throughput":"Current engine state";ui.connections.textContent=String(j.connections??j.seeders??"—");ui.connectionsHint.textContent=j.is_torrent?"Peers / seeders":"Active HTTP connections";ui.remaining.textContent=total?prettyBytes(Math.max(0,total-done)):"—";ui.sizeHint.textContent=total?`${prettyBytes(done)} of ${prettyBytes(total)}`:"Waiting for size";if(j.status==="complete"){state("Complete");ui.jobTitle.textContent="Ready to download";ui.download.hidden=false;ui.pause.hidden=true;ui.resume.hidden=true;ui.cancel.hidden=true;ui.download.onclick=()=>{window.location.href=`${API}/v1/jobs/${encodeURIComponent(j.id)}/file`};clearInterval(pollTimer);pollTimer=null;setProgress(100)}else if(j.status==="paused"){state("Paused","warn");ui.pause.hidden=true;ui.resume.hidden=false}else if(j.status==="error"||j.status==="removed"){state("Error","bad");ui.jobTitle.textContent="Download stopped";clearInterval(pollTimer);pollTimer=null;diag("Engine",j.error_message||"Download failed","bad")}else{state(j.status||"Downloading");ui.pause.hidden=false;ui.resume.hidden=true}}catch(e){ui.sourceSpeedHint.textContent="Backend temporarily unreachable"}}
  async function jobAction(action){if(!currentJob?.id)return;const r=await fetch(`${API}/v1/jobs/${encodeURIComponent(currentJob.id)}/${action}`,{method:"POST"});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||`${action} failed`)}await pollBackendJob()}
  async function startBrowserHttp(source,analysis){ui.jobTitle.textContent=analysis.range_supported?"Browser acceleration ready":"Direct download ready";state("Ready");ui.download.hidden=false;if(!analysis.range_supported||!analysis.size||analysis.size>MAX_BROWSER||analysis.cors_blocked){ui.download.textContent="Open direct download";ui.download.onclick=()=>{const a=document.createElement("a");a.href=source;a.rel="noopener";a.target="_blank";document.body.appendChild(a);a.click();a.remove()};if(analysis.size>MAX_BROWSER)diag("Browser assembly",`Skipped above ${prettyBytes(MAX_BROWSER)}`,"warn");return}ui.download.textContent="Accelerated browser download";ui.download.onclick=async()=>{ui.download.disabled=true;ui.jobTitle.textContent="Downloading segments";state("Downloading");try{const blob=await segmentedFetch(source,analysis.size,8);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=analysis.filename||"download";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);ui.jobTitle.textContent="Download assembled";state("Complete");setProgress(100)}catch(e){state("Error","bad");diag("Browser accelerator",e.message,"bad")}finally{ui.download.disabled=false}}}
  async function segmentedFetch(url,size,workers){const pieces=new Array(workers);let completed=0,started=performance.now();const tasks=Array.from({length:workers},async(_,i)=>{const start=Math.floor(size*i/workers),end=i===workers-1?size-1:Math.floor(size*(i+1)/workers)-1;const r=await fetch(url,{headers:{Range:`bytes=${start}-${end}`},mode:"cors"});if(r.status!==206)throw new Error("Source stopped honoring byte-range requests.");const buf=await r.arrayBuffer();pieces[i]=buf;completed+=buf.byteLength;const seconds=Math.max(.001,(performance.now()-started)/1000);ui.sourceSpeed.textContent=prettySpeed(completed/seconds);ui.connections.textContent=String(workers);ui.connectionsHint.textContent="Parallel browser ranges";ui.remaining.textContent=prettyBytes(size-completed);setProgress(completed/size*100)});await Promise.all(tasks);return new Blob(pieces)}
  async function startBrowserMagnet(source){if(!window.WebTorrent)throw new Error("WebTorrent library did not load.");if(webTorrentClient)try{webTorrentClient.destroy()}catch{}webTorrentClient=new WebTorrent();ui.jobTitle.textContent="Joining WebRTC swarm";state("Connecting");ui.cancel.hidden=false;ui.cancel.onclick=()=>{webTorrentClient?.destroy();state("Cancelled","warn")};webTorrentClient.add(source,torrent=>{ui.filename.textContent=torrent.name||"Torrent download";ui.jobTitle.textContent="Downloading from web peers";state("Downloading");diag("Torrent metadata","Received","ok");diag("Browser swarm","WebRTC peers only","warn");const tick=setInterval(()=>{if(torrent.destroyed){clearInterval(tick);return}setProgress((torrent.progress||0)*100);ui.sourceSpeed.textContent=prettySpeed(torrent.downloadSpeed||0);ui.connections.textContent=String(torrent.numPeers||0);ui.connectionsHint.textContent="WebRTC peers";ui.remaining.textContent=prettyBytes(Math.max(0,(torrent.length||0)-(torrent.downloaded||0)));ui.sizeHint.textContent=torrent.length?`${prettyBytes(torrent.downloaded)} of ${prettyBytes(torrent.length)}`:"Waiting for metadata";if(torrent.done){clearInterval(tick);state("Complete");setProgress(100);ui.jobTitle.textContent="Torrent complete";ui.cancel.hidden=true;if(torrent.files.length===1){ui.download.hidden=false;ui.download.textContent="Download file";ui.download.onclick=()=>torrent.files[0].getBlobURL((err,url)=>{if(err)return toast(err.message);const a=document.createElement("a");a.href=url;a.download=torrent.files[0].name;document.body.appendChild(a);a.click();a.remove()})}else{diag("Files",`${torrent.files.length} files — use Accelerator Mode for large multi-file delivery`,"warn")}}},500)})}
  async function submit(source){resetJobUi();showWorkspace();try{const analysis=API?await backendAnalyze(source):await browserAnalyze(source);renderAnalysis(analysis);if(API)await createBackendJob(source);else if(analysis.type==="magnet")await startBrowserMagnet(source);else await startBrowserHttp(source,analysis)}catch(e){state("Error","bad");ui.jobTitle.textContent="Could not start";ui.filename.textContent="Check the source and try again";diag("Error",e.message||"Unknown error","bad")}}
  ui.form.addEventListener("submit",e=>{e.preventDefault();const source=ui.input.value.trim();if(!source)return toast("Paste a URL or magnet first.");submit(source)});ui.paste.addEventListener("click",async()=>{try{ui.input.value=await navigator.clipboard.readText();ui.input.dispatchEvent(new Event("input"))}catch{toast("Clipboard access was blocked. Paste into the box manually.")}});ui.clear.addEventListener("click",()=>{ui.input.value="";ui.workspace.hidden=true;clearInterval(pollTimer);if(webTorrentClient)try{webTorrentClient.destroy()}catch{}currentJob=null});ui.input.addEventListener("input",()=>{ui.input.style.height="auto";ui.input.style.height=`${Math.min(ui.input.scrollHeight,132)}px`});ui.pause.addEventListener("click",()=>jobAction("pause").catch(e=>toast(e.message)));ui.resume.addEventListener("click",()=>jobAction("resume").catch(e=>toast(e.message)));ui.cancel.addEventListener("click",()=>{if(API)jobAction("cancel").catch(e=>toast(e.message))});window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;ui.install.hidden=false});ui.install.addEventListener("click",async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;ui.install.hidden=true});if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});setMode();
})();
